[general]
import = [ "dracula.toml" ]

[env]
TERM = "xterm-256color"

[window]
# opacity = 0.95
startup_mode = "Maximized"
# dimensions = { columns = 120, lines = 40 }
# position = { x = 250, y = 45 }

[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 11

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Right", mods = "Shift", action = "Copy" },
{ mouse = "Left", action = "ExpandSelection" },
]

[terminal]
shell = "bash"
