[general]
import = [
    # Catppuccin color scheme
    # uncomment the flavour you want below:
    # "catppuccin-latte.toml"
    # "catppuccin-frappe.toml"
    # "catppuccin-macchiato.toml"
    # "catppuccin-mocha.toml"
    "dracula.toml"
]

[env]
TERM = "xterm-256color"

[window]
# opacity = 0.95
dynamic_title = false

[font]
normal = { family = "JetBrainsMonoNLNerdFont", style = "Regular" }
size = 18

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
{ mouse = "Right", mods = "Shift", action = "Copy" },
{ mouse = "Left", action = "ExpandSelection" },
]
