# Options
set -g default-terminal "tmux-256color"
set -ag terminal-features ",*:RGB"
set -g mouse on
set -g focus-events on
set -sg escape-time 0
set -g prefix C-s
set -g base-index 1
set -g detach-on-destroy off

# Keybindings
set -g mode-keys vi
set -g status-keys emacs
bind R source ~/.tmux.conf \; display-message "Config reloaded"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind C command-prompt -p "Command:" "new-window -c '#{pane_current_path}' '%%'"
bind N neww -c "#{pane_current_path}" nvim
bind g neww -n "git" -S -c "#{pane_current_path}" lazygit
bind f run-shell "~/.local/bin/tmux-session-manager"

# Styling message/command line and statusline
set -g message-style "bg=#424242,fg=#b0bec5"
set -g message-command-style "bg=#424242,fg=#b0bec5"
set -g status-style "bg=#212121 fg=#b0bec5"
set -g status-position top
set -g status-left "#S"
set -g status-left-length 100
set -g status-right "%H:%M"
set -g status-justify absolute-centre
