[main]
terminal=kitty -e
font=Hack Nerd Font:size=8
line-height=12
width=60
# disable those large images:
image-size-ratio=1

[colors]
background=2e3440ff
text=eceff4ff
match=88c0d0ff
selection-match=88c0d0ff
selection=434c5eff
selection-text=eceff4ff
border=5e81acff
