[main]
terminal=kitty -e
font=FiraCode Nerd Font:size=8
line-height=12
width=60
# disable those large images:
image-size-ratio=1

[colors]
background=#282c34ff
text=#abb2bfff
match=#61afefff
selection-match=#61afefff
selection=#393e48ff
selection-text=#979eabff
border=#61afefff
