# ==================================================
# === Basic settings ===
# ==================================================

# Better Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Reload Config
bind R source-file ~/.tmux.conf \; display-message "Config reloaded"

set -g default-terminal "tmux-256color"  # Making sure colors are displayed properly
set -g base-index 1                      # Window indices starts from 1 not 0
set -g pane-base-index 1                 # Pane indices starts from 1 not 0
set -g mouse on                          # Enabling mouse support
set-option -g allow-rename off           # Disabling window auto rename


# ==================================================
# === Configuring Keybindings ===
# ==================================================

set -g status-keys emacs
set -g mode-keys vi
# defaults:
#   begin-selction: space
#   copy-selection: enter
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection

# Custom Keybindings
bind -n C-x switch-client -T prefix-x
bind -T prefix-x C-x send-keys C-x
bind -T prefix-x C-f new-window ~/.local/bin/tmux-sessionizer
bind -T prefix-x f new-window ~/.local/bin/tmux-quicknav
# bind U run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important1/category1"
# bind I run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important2/category1"
# bind O run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important3/category1"
# bind P run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important4/category1"
# bind J run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important1/category2"
# bind K run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important2/category2"
# bind L run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important3/category2"
# bind ; run-shell "~/.local/bin/tmux-sessionizer /path/to/something/important4/category2"


# ==================================================
# === Configuring Theme ===
# ==================================================

#+---------+
#+ Options +
#+---------+
set -g status-interval 1
set -g status on

#+--------+
#+ Status +
#+--------+
#+--- Layout ---+
set -g status-justify left

#+--- Colors ---+
set -g status-style bg=black,fg=white

#+--- Bars ---+
set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
set -g status-left-length 100
set -g status-right "#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %Y-%m-%d #[fg=white,bg=brightblack,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] %H:%M #[fg=blue,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=blue,bold] #H "

#+--- Windows ---+
set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
set -g window-status-separator ""

#+-------+
#+ Panes +
#+-------+
set -g pane-border-style bg=default,fg=brightblack
set -g pane-active-border-style bg=default,fg=blue
set -g display-panes-colour black
set -g display-panes-active-colour brightblack

#+------------+
#+ Clock Mode +
#+------------+
setw -g clock-mode-colour cyan

#+----------+
#+ Messages +
#+----------+
set -g message-style bg=brightblack,fg=cyan
set -g message-command-style bg=brightblack,fg=cyan
